### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [JosephBarber96/FinalProject#1]
Hello, under what license is this project released under ? I would like to study it and learn from it. Thank-you.

**Comment by JosephBarber96** [comment]
Hello, 

Since this work was done while in University, and was mostly intended to be seen by my lecturers, I never officially added a license to this repository/project. However, I'm happy for you to read, study and/or use this code. When I get some free time later I will attach a license to this repository 

Thanks!

**Comment by JosephBarber96** [comment]
I've now attached a licence to the repository: https://github.com/JosephBarber96/FinalProject/blob/master/LICENSE
